version: "3.8"

services:
  nginx:
    container_name: "server"
    image: nginx:1.23.3-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./site/public:/home/public
    ports:
      - 8080:80
    tty: true
    depends_on:
      - app
  app:
    container_name: "hexo"
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./site:/home/site
    stdin_open: true
    tty: true
    command: /bin/sh
